apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: goprasadnodejsdockerhelloworld 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goprasadnodejsdockerhelloworld 
    spec:
      containers:
        - name: goprasadnodejsdockerhelloworld 
          image: prgorle.azurecr.io/goprasadnodejsdockerhelloworld
          ports:
          - containerPort: 8080